"""removes for now tags and hash_id columns from Lesson

Revision ID: 0c9fc0685667
Revises: 94712f6ec875
Create Date: 2020-06-09 00:41:10.386547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9fc0685667'
down_revision = '94712f6ec875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson') as batch_op:
        batch_op.drop_column('hash_id')
        batch_op.drop_column('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('tags', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    op.add_column('lesson', sa.Column('hash_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
