"""empty message

Revision ID: 540f0ebe6e4d
Revises: 66892a54820e
Create Date: 2020-06-07 02:39:04.410933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540f0ebe6e4d'
down_revision = '66892a54820e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('hash_id', sa.String(length=120), nullable=True))
    op.drop_column('user', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tags', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    op.drop_column('lesson', 'hash_id')
    # ### end Alembic commands ###
