"""add tags to User and Lesson tables

Revision ID: 66892a54820e
Revises: 753cd1f71c72
Create Date: 2020-06-05 08:10:45.284051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66892a54820e'
down_revision = '753cd1f71c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('tags', sa.Unicode(length=240), nullable=True))
    op.create_index(op.f('ix_tlahtolli_word'), 'tlahtolli', ['word'], unique=False)
    op.add_column('user', sa.Column('tags', sa.Unicode(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tags')
    op.drop_index(op.f('ix_tlahtolli_word'), table_name='tlahtolli')
    op.drop_column('lesson', 'tags')
    # ### end Alembic commands ###
