"""adds liked_by attribute to Lesson table

Revision ID: a77cbe564bba
Revises: 540f0ebe6e4d
Create Date: 2020-06-07 03:07:57.246947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77cbe564bba'
down_revision = '540f0ebe6e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('liked_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lesson', 'user', ['liked_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'liked_by')
    # ### end Alembic commands ###
